/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LOL;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import rest.DAO.ClientDAO;
import rest.DAO.ClientDAO;
import rest.DAO.UserDAO;
import rest.DAO.UserDAO;
import rest.entities.Client;
import rest.entities.User;

/**
 *
 * @author lenovo
 */
public class GestionClient extends javax.swing.JFrame {

    /**
     * Creates new form Gestion_Client
     */
    public class ClientModel extends AbstractTableModel {

        private String[] columnNames = {"Login", "Nom", "Prenom", "Cin", "Adresse", "Mail", "Tel"};
        private List<Object> dat;

        public ClientModel() {
            dat = ClientDAO.getInstance().displayAll();

        }

        @Override
        public int getRowCount() {
            return dat.size();
        }

        @Override
        public int getColumnCount() {
            return columnNames.length;
        }

        @Override
        public Object getValueAt(int rowIndex, int ColumnIndex) {
            Client re = (Client) dat.get(rowIndex);
            switch (ColumnIndex) {
                case 0:
                    return re.getLogin();
                case 1:
                    return re.getNom();
                case 2:
                    return re.getPrenom();
                case 3:
                    return re.getCin();
                case 4:
                    return re.getAdresse();
                case 5:
                    return re.getMail();
                case 6:
                    return re.getTelephone();
                default:
                    return null;
            }

        }

        @Override
        public String getColumnName(int col) {
            return columnNames[col]; //To change body of generated methods, choose Tools | Templates.
        }

        public void removeRow(int row) {
          
            fireTableRowsDeleted(row, row);
        }
    }

    public GestionClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableClient = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        SupprimerUtilisateur = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion des utilisateurs");

        TableClient.setModel(new ClientModel());
        TableClient.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TableClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableClientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableClient);

        jLabel1.setText("Liste des clients");

        SupprimerUtilisateur.setText("Supprimer");
        SupprimerUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerUtilisateurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 491, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SupprimerUtilisateur)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(SupprimerUtilisateur)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SupprimerUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerUtilisateurActionPerformed
        if (TableClient.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "aucun commentaire");
        } else {
            if (TableClient.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(null, "aucun commentaire selectionner");
            } else {
                Client c = new Client();
                c.setCin(Integer.parseInt(TableClient.getValueAt(TableClient.getSelectedRow(), 3).toString()));
                ClientDAO.getInstance().delete(c);

                User usr = new User(TableClient.getValueAt(TableClient.getSelectedRow(), 1).toString(), "");
                UserDAO.getInstance().delete(usr);

                JOptionPane.showMessageDialog(null, "Le Client a été supprimer avec succée");
            }
        }
    }//GEN-LAST:event_SupprimerUtilisateurActionPerformed

    private void TableClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableClientMouseClicked
    }//GEN-LAST:event_TableClientMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionClient().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SupprimerUtilisateur;
    private javax.swing.JTable TableClient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
